export const APPLICATION_SUBMIT_REQUEST = 'APPLICATION_SUBMIT_REQUEST';
export const APPLICATION_SUBMIT_SUCCESS = 'APPLICATION_SUBMIT_SUCCESS';
export const APPLICATION_SUBMIT_FAIL = 'APPLICATION_SUBMIT_FAIL';

export const APPLICATION_LIST_REQUEST = 'APPLICATION_LIST_REQUEST';
export const APPLICATION_LIST_SUCCESS = 'APPLICATION_LIST_SUCCESS';
export const APPLICATION_LIST_FAIL = 'APPLICATION_LIST_FAIL';

export const APPLICATION_ACTION_REQUEST = 'APPLICATION_ACTION_REQUEST';
export const APPLICATION_ACTION_SUCCESS = 'APPLICATION_ACTION_SUCCESS';
export const APPLICATION_ACTION_FAIL = 'APPLICATION_ACTION_FAIL';
