export const SUBSCRIPTION_TIER_LIST_REQUEST = 'SUBSCRIPTION_TIER_LIST_REQUEST';
export const SUBSCRIPTION_TIER_LIST_SUCCESS = 'SUBSCRIPTION_TIER_LIST_SUCCESS';
export const SUBSCRIPTION_TIER_LIST_FAIL = 'SUBSCRIPTION_TIER_LIST_FAIL';

export const SUBSCRIPTION_CREATE_REQUEST = 'SUBSCRIPTION_CREATE_REQUEST';
export const SUBSCRIPTION_CREATE_SUCCESS = 'SUBSCRIPTION_CREATE_SUCCESS';
export const SUBSCRIPTION_CREATE_FAIL = 'SUBSCRIPTION_CREATE_FAIL';

export const SUBSCRIPTION_CURRENT_REQUEST = 'SUBSCRIPTION_CURRENT_REQUEST';
export const SUBSCRIPTION_CURRENT_SUCCESS = 'SUBSCRIPTION_CURRENT_SUCCESS';
export const SUBSCRIPTION_CURRENT_FAIL = 'SUBSCRIPTION_CURRENT_FAIL';

export const SUBSCRIPTION_LIST_REQUEST = 'SUBSCRIPTION_LIST_REQUEST';
export const SUBSCRIPTION_LIST_SUCCESS = 'SUBSCRIPTION_LIST_SUCCESS';
export const SUBSCRIPTION_LIST_FAIL = 'SUBSCRIPTION_LIST_FAIL';
